### ISSUE TITLE
Bloodpack Extraction wrong name insert

### ISSUE THREAD

**Issue by DreamScout** [ark-automated/Ark-Automated#1]
Hi.
First thx for the program.
I have problems with the blood extraction.
Everything work but sometimes the program fill the wrong name in the search bar. There ist "Blood Extraction Syringe Brew" in the search field and the script stop.
I dont know why.
Thx

**Comment by ark-automated** [comment]
Hi @DreamScout 
Could you perhaps make a video? And are you using the Tek Pod or medical brew method with the BloodPackFarmer? If you run use latter I assume that there is an error with the search bar not getting cleared properly. Would be easy to confirm with a video :)

Olivier

**Comment by DreamScout** [comment]
https://youtu.be/C4jYu7JyLwM
https://youtu.be/n5nsyJedeQM

**Comment by ark-automated** [comment]
Thanks for the videos, my apologies for the late response. I think I know what is triggering it and I'll try to fix it in the next major version. For now you could increase the sleep here https://github.com/ark-automated/Ark-Automated/blob/master/Ark_Automated%20V0.41.ahk#L518 as it might be trying to select/replace the text too fast for your computer

**Comment by DreamScout** [comment]
How can i change the sleep timer. Where? How? I think its not my PC. Its the lagging server.

**Comment by ark-automated** [comment]
> 
> 
> How can i change the sleep timer. Where? How? I think its not my PC. Its the lagging server.

Are you running the .exe or the .ahk? If you are running the .exe I can modify the code and send you the modified .exe with the longer sleep timers. 

If you run the .ahk script you could extend the sleep timer on line 518(as linked above) and line 539+541 to 100ms. 

Also just to verify, ctrl+a does select all your text in the search bar when pressed manually, correct?

**Comment by DreamScout** [comment]
Hi.

 

Yes with CRTL+A it select all the text.

I use the Exe. Programm.

 

It would be very nice if you can modifiy it for me 😊

I hope it works.

 

Thx

 

Von: ark-automated <notifications@github.com> 
Gesendet: Donnerstag, 18. Februar 2021 16:40
An: ark-automated/Ark-Automated <Ark-Automated@noreply.github.com>
Cc: DreamScout <info@andreasmargreiter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ark-automated/Ark-Automated] Bloodpack Extraction wrong name insert (#1)

 

How can i change the sleep timer. Where? How? I think its not my PC. Its the lagging server.

Are you running the .exe or the .ahk? If you are running the .exe I can modify the code and send you the modified .exe with the longer sleep timers.

If you run the .ahk script you could extend the sleep timer on line 518(as linked above) and line 539+541 to 100ms.

Also just to verify, ctrl+a does select all your text in the search bar when pressed manually, correct?

**Comment by ark-automated** [comment]
Sorry for all the delays, very busy with irl things, this version has longer sleep timers when trying to send the text in the search field:

[Ark_Automated V0.41_FOR_DREAMSCOUT.zip](https://github.com/ark-automated/Ark-Automated/files/6083130/Ark_Automated.V0.41_FOR_DREAMSCOUT.zip)
